export const Icons = {
  search: require('../assets/search.png'),
  more: require('../assets/more.png'),
  house: require('../assets/house.json'),
  garden: require('../assets/garden.jpg'),
  rightArrow: require('../assets/right-arrow.png'),
  close: require('../assets/close.png'),
  heart: require('../assets/heart.png'),
  leftArrow: require('../assets/left-arrow.png'),
  map: require('../assets/map.png'),
  pin: require('../assets/pin.png'),
  pulse: require('../assets/pulse.png'),
  user: require('../assets/user.png'),
  furniture: require('../assets/furniture.png'),
  zoomIn: require('../assets/zoom-in.png'),
};
